apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
    servicefor: hello
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      servicefor: hello
  strategy: {}
  template:
    metadata:
      labels:
        app: hello
        servicefor: hello
    spec:
      containers:
        - image: opencloudnatives/hello:init
          imagePullPolicy: Always
          name: hello