apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
    servicefor: hello
  name: hello
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: hello
    servicefor: hello
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hello
    servicefor: hello
  name: hello
spec:
    containers:
      - image: opencloudnatives/hello:init
        imagePullPolicy: Always
        name: hello
        ports:
          - containerPort: 8080
